### ISSUE TITLE
Unable to output to sibling of parent directory.

### ISSUE THREAD

**Issue by oagix** [sanjsanj/webpack-entry-plus#1]
Hello,

I've got an issue using the module.

I am trying to make all files matching /source/js/*.js compile to a sibling folder in the parent folder of each script. Anything I try will just go to */dist/[path] - which is not what's intended. When I set the path to root so that it matches, it says permission denied. Any thoughts?

![image](https://user-images.githubusercontent.com/8274669/63609829-a306f880-c5e0-11e9-85a7-4f62e0f63ee5.png)

@sanjsanj

**Comment by Abruptive** [comment]
Instead of outputting to /includes, here's what it does without the `path` setting:

![image](https://user-images.githubusercontent.com/8274669/63610915-4bb65780-c5e3-11e9-8eb6-990ee0222162.png)

**Comment by sanjsanj** [comment]
Hi @Abruptive , sorry to hear you're having issues.

Some questions that might help narrow it down:

What version of webpack are you using?  This package was built a long time ago and not tested with v4, although I've been told it works ok and not received any other bugs.  Not saying it does work flawlessly, I've not tested it myself so it might be a version problem.

Are you declaring `dist` as your output path anywhere in your config?  I think this sounds like a likely suspect.  You should follow the advice here https://webpack.js.org/configuration/output/#outputpath

What you have there should technically work, you shouldn't need the `path`, and your `filename` should be `[name]`

**Comment by sanjsanj** [comment]
Closing the issue for now, just reply if it's still a problem.
